<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Remote.Application\Remote.Application.csproj" />
    <ProjectReference Include="..\Remote.Protocols\Remote.Protocols.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="Porta.Pty" Version="2.2.2" />
  </ItemGroup>
</Project>
